// Generated by gencpp from file tricat_msgs/Control.msg
// DO NOT EDIT!


#ifndef TRICAT_MSGS_MESSAGE_CONTROL_H
#define TRICAT_MSGS_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/UInt16.h>
#include <std_msgs/UInt16.h>
#include <std_msgs/UInt16.h>
#include <std_msgs/UInt16.h>

namespace tricat_msgs
{
template <class ContainerAllocator>
struct Control_
{
  typedef Control_<ContainerAllocator> Type;

  Control_()
    : header()
    , servo_s()
    , servo_p()
    , thruster_p()
    , thruster_s()  {
    }
  Control_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , servo_s(_alloc)
    , servo_p(_alloc)
    , thruster_p(_alloc)
    , thruster_s(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _servo_s_type;
  _servo_s_type servo_s;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _servo_p_type;
  _servo_p_type servo_p;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _thruster_p_type;
  _thruster_p_type thruster_p;

   typedef  ::std_msgs::UInt16_<ContainerAllocator>  _thruster_s_type;
  _thruster_s_type thruster_s;





  typedef boost::shared_ptr< ::tricat_msgs::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tricat_msgs::Control_<ContainerAllocator> const> ConstPtr;

}; // struct Control_

typedef ::tricat_msgs::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::tricat_msgs::Control > ControlPtr;
typedef boost::shared_ptr< ::tricat_msgs::Control const> ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tricat_msgs::Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tricat_msgs::Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tricat_msgs::Control_<ContainerAllocator1> & lhs, const ::tricat_msgs::Control_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.servo_s == rhs.servo_s &&
    lhs.servo_p == rhs.servo_p &&
    lhs.thruster_p == rhs.thruster_p &&
    lhs.thruster_s == rhs.thruster_s;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tricat_msgs::Control_<ContainerAllocator1> & lhs, const ::tricat_msgs::Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tricat_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tricat_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tricat_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tricat_msgs::Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tricat_msgs::Control_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tricat_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tricat_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tricat_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0e90ce225824dce6ea0018e8f0cbd3f";
  }

  static const char* value(const ::tricat_msgs::Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0e90ce225824dceULL;
  static const uint64_t static_value2 = 0x6ea0018e8f0cbd3fULL;
};

template<class ContainerAllocator>
struct DataType< ::tricat_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tricat_msgs/Control";
  }

  static const char* value(const ::tricat_msgs::Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tricat_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/UInt16 servo_s\n"
"std_msgs/UInt16 servo_p\n"
"std_msgs/UInt16 thruster_p\n"
"std_msgs/UInt16 thruster_s\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt16\n"
"uint16 data\n"
;
  }

  static const char* value(const ::tricat_msgs::Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tricat_msgs::Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.servo_s);
      stream.next(m.servo_p);
      stream.next(m.thruster_p);
      stream.next(m.thruster_s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tricat_msgs::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tricat_msgs::Control_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "servo_s: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.servo_s);
    s << indent << "servo_p: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.servo_p);
    s << indent << "thruster_p: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.thruster_p);
    s << indent << "thruster_s: ";
    s << std::endl;
    Printer< ::std_msgs::UInt16_<ContainerAllocator> >::stream(s, indent + "  ", v.thruster_s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRICAT_MSGS_MESSAGE_CONTROL_H
