# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tricat_msgs/WP.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class WP(genpy.Message):
  _md5sum = "e86d166212e6ad49f8865c7a6bb74d08"
  _type = "tricat_msgs/WP"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Float64 x
std_msgs/Float64 y
std_msgs/String type
std_msgs/UInt16 num
std_msgs/UInt16 range
std_msgs/Bool arrive
================================================================================
MSG: std_msgs/Float64
float64 data
================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: std_msgs/UInt16
uint16 data

================================================================================
MSG: std_msgs/Bool
bool data"""
  __slots__ = ['x','y','type','num','range','arrive']
  _slot_types = ['std_msgs/Float64','std_msgs/Float64','std_msgs/String','std_msgs/UInt16','std_msgs/UInt16','std_msgs/Bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,type,num,range,arrive

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WP, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = std_msgs.msg.Float64()
      if self.y is None:
        self.y = std_msgs.msg.Float64()
      if self.type is None:
        self.type = std_msgs.msg.String()
      if self.num is None:
        self.num = std_msgs.msg.UInt16()
      if self.range is None:
        self.range = std_msgs.msg.UInt16()
      if self.arrive is None:
        self.arrive = std_msgs.msg.Bool()
    else:
      self.x = std_msgs.msg.Float64()
      self.y = std_msgs.msg.Float64()
      self.type = std_msgs.msg.String()
      self.num = std_msgs.msg.UInt16()
      self.range = std_msgs.msg.UInt16()
      self.arrive = std_msgs.msg.Bool()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d().pack(_x.x.data, _x.y.data))
      _x = self.type.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2HB().pack(_x.num.data, _x.range.data, _x.arrive.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x is None:
        self.x = std_msgs.msg.Float64()
      if self.y is None:
        self.y = std_msgs.msg.Float64()
      if self.type is None:
        self.type = std_msgs.msg.String()
      if self.num is None:
        self.num = std_msgs.msg.UInt16()
      if self.range is None:
        self.range = std_msgs.msg.UInt16()
      if self.arrive is None:
        self.arrive = std_msgs.msg.Bool()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.x.data, _x.y.data,) = _get_struct_2d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type.data = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.num.data, _x.range.data, _x.arrive.data,) = _get_struct_2HB().unpack(str[start:end])
      self.arrive.data = bool(self.arrive.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d().pack(_x.x.data, _x.y.data))
      _x = self.type.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2HB().pack(_x.num.data, _x.range.data, _x.arrive.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x is None:
        self.x = std_msgs.msg.Float64()
      if self.y is None:
        self.y = std_msgs.msg.Float64()
      if self.type is None:
        self.type = std_msgs.msg.String()
      if self.num is None:
        self.num = std_msgs.msg.UInt16()
      if self.range is None:
        self.range = std_msgs.msg.UInt16()
      if self.arrive is None:
        self.arrive = std_msgs.msg.Bool()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.x.data, _x.y.data,) = _get_struct_2d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type.data = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.num.data, _x.range.data, _x.arrive.data,) = _get_struct_2HB().unpack(str[start:end])
      self.arrive.data = bool(self.arrive.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2HB = None
def _get_struct_2HB():
    global _struct_2HB
    if _struct_2HB is None:
        _struct_2HB = struct.Struct("<2HB")
    return _struct_2HB
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
