# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tricat_msgs/WaypointServiceRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WaypointServiceRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "tricat_msgs/WaypointServiceRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Request
"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WaypointServiceRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tricat_msgs/WaypointServiceResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg
import tricat_msgs.msg

class WaypointServiceResponse(genpy.Message):
  _md5sum = "bbca728dc1a971940e618ed2a281f3e2"
  _type = "tricat_msgs/WaypointServiceResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Response
WPList waypoint_list

================================================================================
MSG: tricat_msgs/WPList
std_msgs/Header header
tricat_msgs/WP[] WP_data
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: tricat_msgs/WP
std_msgs/Float64 x
std_msgs/Float64 y
std_msgs/String type
std_msgs/UInt16 num
std_msgs/UInt16 range
std_msgs/Bool arrive
================================================================================
MSG: std_msgs/Float64
float64 data
================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: std_msgs/UInt16
uint16 data

================================================================================
MSG: std_msgs/Bool
bool data"""
  __slots__ = ['waypoint_list']
  _slot_types = ['tricat_msgs/WPList']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       waypoint_list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WaypointServiceResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.waypoint_list is None:
        self.waypoint_list = tricat_msgs.msg.WPList()
    else:
      self.waypoint_list = tricat_msgs.msg.WPList()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.waypoint_list.header.seq, _x.waypoint_list.header.stamp.secs, _x.waypoint_list.header.stamp.nsecs))
      _x = self.waypoint_list.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.waypoint_list.WP_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoint_list.WP_data:
        _v1 = val1.x
        _x = _v1.data
        buff.write(_get_struct_d().pack(_x))
        _v2 = val1.y
        _x = _v2.data
        buff.write(_get_struct_d().pack(_x))
        _v3 = val1.type
        _x = _v3.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v4 = val1.num
        _x = _v4.data
        buff.write(_get_struct_H().pack(_x))
        _v5 = val1.range
        _x = _v5.data
        buff.write(_get_struct_H().pack(_x))
        _v6 = val1.arrive
        _x = _v6.data
        buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.waypoint_list is None:
        self.waypoint_list = tricat_msgs.msg.WPList()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.waypoint_list.header.seq, _x.waypoint_list.header.stamp.secs, _x.waypoint_list.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.waypoint_list.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.waypoint_list.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoint_list.WP_data = []
      for i in range(0, length):
        val1 = tricat_msgs.msg.WP()
        _v7 = val1.x
        start = end
        end += 8
        (_v7.data,) = _get_struct_d().unpack(str[start:end])
        _v8 = val1.y
        start = end
        end += 8
        (_v8.data,) = _get_struct_d().unpack(str[start:end])
        _v9 = val1.type
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v9.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v9.data = str[start:end]
        _v10 = val1.num
        start = end
        end += 2
        (_v10.data,) = _get_struct_H().unpack(str[start:end])
        _v11 = val1.range
        start = end
        end += 2
        (_v11.data,) = _get_struct_H().unpack(str[start:end])
        _v12 = val1.arrive
        start = end
        end += 1
        (_v12.data,) = _get_struct_B().unpack(str[start:end])
        _v12.data = bool(_v12.data)
        self.waypoint_list.WP_data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.waypoint_list.header.seq, _x.waypoint_list.header.stamp.secs, _x.waypoint_list.header.stamp.nsecs))
      _x = self.waypoint_list.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.waypoint_list.WP_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoint_list.WP_data:
        _v13 = val1.x
        _x = _v13.data
        buff.write(_get_struct_d().pack(_x))
        _v14 = val1.y
        _x = _v14.data
        buff.write(_get_struct_d().pack(_x))
        _v15 = val1.type
        _x = _v15.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v16 = val1.num
        _x = _v16.data
        buff.write(_get_struct_H().pack(_x))
        _v17 = val1.range
        _x = _v17.data
        buff.write(_get_struct_H().pack(_x))
        _v18 = val1.arrive
        _x = _v18.data
        buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.waypoint_list is None:
        self.waypoint_list = tricat_msgs.msg.WPList()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.waypoint_list.header.seq, _x.waypoint_list.header.stamp.secs, _x.waypoint_list.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.waypoint_list.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.waypoint_list.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoint_list.WP_data = []
      for i in range(0, length):
        val1 = tricat_msgs.msg.WP()
        _v19 = val1.x
        start = end
        end += 8
        (_v19.data,) = _get_struct_d().unpack(str[start:end])
        _v20 = val1.y
        start = end
        end += 8
        (_v20.data,) = _get_struct_d().unpack(str[start:end])
        _v21 = val1.type
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v21.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v21.data = str[start:end]
        _v22 = val1.num
        start = end
        end += 2
        (_v22.data,) = _get_struct_H().unpack(str[start:end])
        _v23 = val1.range
        start = end
        end += 2
        (_v23.data,) = _get_struct_H().unpack(str[start:end])
        _v24 = val1.arrive
        start = end
        end += 1
        (_v24.data,) = _get_struct_B().unpack(str[start:end])
        _v24.data = bool(_v24.data)
        self.waypoint_list.WP_data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_H = None
def _get_struct_H():
    global _struct_H
    if _struct_H is None:
        _struct_H = struct.Struct("<H")
    return _struct_H
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
class WaypointService(object):
  _type          = 'tricat_msgs/WaypointService'
  _md5sum = 'bbca728dc1a971940e618ed2a281f3e2'
  _request_class  = WaypointServiceRequest
  _response_class = WaypointServiceResponse
