// Generated by gencpp from file tricat_msgs/ObstacleList.msg
// DO NOT EDIT!


#ifndef TRICAT_MSGS_MESSAGE_OBSTACLELIST_H
#define TRICAT_MSGS_MESSAGE_OBSTACLELIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tricat_msgs/Obstacle.h>

namespace tricat_msgs
{
template <class ContainerAllocator>
struct ObstacleList_
{
  typedef ObstacleList_<ContainerAllocator> Type;

  ObstacleList_()
    : lidar_header()
    , obstacle()  {
    }
  ObstacleList_(const ContainerAllocator& _alloc)
    : lidar_header(_alloc)
    , obstacle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _lidar_header_type;
  _lidar_header_type lidar_header;

   typedef std::vector< ::tricat_msgs::Obstacle_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tricat_msgs::Obstacle_<ContainerAllocator> >> _obstacle_type;
  _obstacle_type obstacle;





  typedef boost::shared_ptr< ::tricat_msgs::ObstacleList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tricat_msgs::ObstacleList_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleList_

typedef ::tricat_msgs::ObstacleList_<std::allocator<void> > ObstacleList;

typedef boost::shared_ptr< ::tricat_msgs::ObstacleList > ObstacleListPtr;
typedef boost::shared_ptr< ::tricat_msgs::ObstacleList const> ObstacleListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tricat_msgs::ObstacleList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tricat_msgs::ObstacleList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tricat_msgs::ObstacleList_<ContainerAllocator1> & lhs, const ::tricat_msgs::ObstacleList_<ContainerAllocator2> & rhs)
{
  return lhs.lidar_header == rhs.lidar_header &&
    lhs.obstacle == rhs.obstacle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tricat_msgs::ObstacleList_<ContainerAllocator1> & lhs, const ::tricat_msgs::ObstacleList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tricat_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tricat_msgs::ObstacleList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tricat_msgs::ObstacleList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tricat_msgs::ObstacleList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tricat_msgs::ObstacleList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tricat_msgs::ObstacleList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tricat_msgs::ObstacleList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tricat_msgs::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e58b9c6e530a428f4aad1beec1ae1b08";
  }

  static const char* value(const ::tricat_msgs::ObstacleList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe58b9c6e530a428fULL;
  static const uint64_t static_value2 = 0x4aad1beec1ae1b08ULL;
};

template<class ContainerAllocator>
struct DataType< ::tricat_msgs::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tricat_msgs/ObstacleList";
  }

  static const char* value(const ::tricat_msgs::ObstacleList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tricat_msgs::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header lidar_header\n"
"tricat_msgs/Obstacle[] obstacle\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tricat_msgs/Obstacle\n"
"geometry_msgs/Point begin\n"
"geometry_msgs/Point end\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tricat_msgs::ObstacleList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tricat_msgs::ObstacleList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lidar_header);
      stream.next(m.obstacle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tricat_msgs::ObstacleList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tricat_msgs::ObstacleList_<ContainerAllocator>& v)
  {
    s << indent << "lidar_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.lidar_header);
    s << indent << "obstacle[]" << std::endl;
    for (size_t i = 0; i < v.obstacle.size(); ++i)
    {
      s << indent << "  obstacle[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tricat_msgs::Obstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRICAT_MSGS_MESSAGE_OBSTACLELIST_H
