// Generated by gencpp from file tricat_msgs/Sensor_total.msg
// DO NOT EDIT!


#ifndef TRICAT_MSGS_MESSAGE_SENSOR_TOTAL_H
#define TRICAT_MSGS_MESSAGE_SENSOR_TOTAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <std_msgs/Float64.h>

namespace tricat_msgs
{
template <class ContainerAllocator>
struct Sensor_total_
{
  typedef Sensor_total_<ContainerAllocator> Type;

  Sensor_total_()
    : header()
    , position_ned()
    , psi()  {
    }
  Sensor_total_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position_ned(_alloc)
    , psi(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_ned_type;
  _position_ned_type position_ned;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _psi_type;
  _psi_type psi;





  typedef boost::shared_ptr< ::tricat_msgs::Sensor_total_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tricat_msgs::Sensor_total_<ContainerAllocator> const> ConstPtr;

}; // struct Sensor_total_

typedef ::tricat_msgs::Sensor_total_<std::allocator<void> > Sensor_total;

typedef boost::shared_ptr< ::tricat_msgs::Sensor_total > Sensor_totalPtr;
typedef boost::shared_ptr< ::tricat_msgs::Sensor_total const> Sensor_totalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tricat_msgs::Sensor_total_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tricat_msgs::Sensor_total_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tricat_msgs::Sensor_total_<ContainerAllocator1> & lhs, const ::tricat_msgs::Sensor_total_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position_ned == rhs.position_ned &&
    lhs.psi == rhs.psi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tricat_msgs::Sensor_total_<ContainerAllocator1> & lhs, const ::tricat_msgs::Sensor_total_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tricat_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tricat_msgs::Sensor_total_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tricat_msgs::Sensor_total_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tricat_msgs::Sensor_total_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tricat_msgs::Sensor_total_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tricat_msgs::Sensor_total_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tricat_msgs::Sensor_total_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tricat_msgs::Sensor_total_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cfffd2feabde8d02a0b65cd795f0e07d";
  }

  static const char* value(const ::tricat_msgs::Sensor_total_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcfffd2feabde8d02ULL;
  static const uint64_t static_value2 = 0xa0b65cd795f0e07dULL;
};

template<class ContainerAllocator>
struct DataType< ::tricat_msgs::Sensor_total_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tricat_msgs/Sensor_total";
  }

  static const char* value(const ::tricat_msgs::Sensor_total_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tricat_msgs::Sensor_total_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point position_ned\n"
"std_msgs/Float64 psi\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::tricat_msgs::Sensor_total_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tricat_msgs::Sensor_total_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position_ned);
      stream.next(m.psi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sensor_total_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tricat_msgs::Sensor_total_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tricat_msgs::Sensor_total_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position_ned: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position_ned);
    s << indent << "psi: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.psi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRICAT_MSGS_MESSAGE_SENSOR_TOTAL_H
