// Generated by gencpp from file tricat_msgs/WaypointService.msg
// DO NOT EDIT!


#ifndef TRICAT_MSGS_MESSAGE_WAYPOINTSERVICE_H
#define TRICAT_MSGS_MESSAGE_WAYPOINTSERVICE_H

#include <ros/service_traits.h>


#include <tricat_msgs/WaypointServiceRequest.h>
#include <tricat_msgs/WaypointServiceResponse.h>


namespace tricat_msgs
{

struct WaypointService
{

typedef WaypointServiceRequest Request;
typedef WaypointServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WaypointService
} // namespace tricat_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tricat_msgs::WaypointService > {
  static const char* value()
  {
    return "bbca728dc1a971940e618ed2a281f3e2";
  }

  static const char* value(const ::tricat_msgs::WaypointService&) { return value(); }
};

template<>
struct DataType< ::tricat_msgs::WaypointService > {
  static const char* value()
  {
    return "tricat_msgs/WaypointService";
  }

  static const char* value(const ::tricat_msgs::WaypointService&) { return value(); }
};


// service_traits::MD5Sum< ::tricat_msgs::WaypointServiceRequest> should match
// service_traits::MD5Sum< ::tricat_msgs::WaypointService >
template<>
struct MD5Sum< ::tricat_msgs::WaypointServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tricat_msgs::WaypointService >::value();
  }
  static const char* value(const ::tricat_msgs::WaypointServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tricat_msgs::WaypointServiceRequest> should match
// service_traits::DataType< ::tricat_msgs::WaypointService >
template<>
struct DataType< ::tricat_msgs::WaypointServiceRequest>
{
  static const char* value()
  {
    return DataType< ::tricat_msgs::WaypointService >::value();
  }
  static const char* value(const ::tricat_msgs::WaypointServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tricat_msgs::WaypointServiceResponse> should match
// service_traits::MD5Sum< ::tricat_msgs::WaypointService >
template<>
struct MD5Sum< ::tricat_msgs::WaypointServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tricat_msgs::WaypointService >::value();
  }
  static const char* value(const ::tricat_msgs::WaypointServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tricat_msgs::WaypointServiceResponse> should match
// service_traits::DataType< ::tricat_msgs::WaypointService >
template<>
struct DataType< ::tricat_msgs::WaypointServiceResponse>
{
  static const char* value()
  {
    return DataType< ::tricat_msgs::WaypointService >::value();
  }
  static const char* value(const ::tricat_msgs::WaypointServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRICAT_MSGS_MESSAGE_WAYPOINTSERVICE_H
