// Generated by gencpp from file tricat_msgs/WaypointServiceRequest.msg
// DO NOT EDIT!


#ifndef TRICAT_MSGS_MESSAGE_WAYPOINTSERVICEREQUEST_H
#define TRICAT_MSGS_MESSAGE_WAYPOINTSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tricat_msgs
{
template <class ContainerAllocator>
struct WaypointServiceRequest_
{
  typedef WaypointServiceRequest_<ContainerAllocator> Type;

  WaypointServiceRequest_()
    {
    }
  WaypointServiceRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointServiceRequest_

typedef ::tricat_msgs::WaypointServiceRequest_<std::allocator<void> > WaypointServiceRequest;

typedef boost::shared_ptr< ::tricat_msgs::WaypointServiceRequest > WaypointServiceRequestPtr;
typedef boost::shared_ptr< ::tricat_msgs::WaypointServiceRequest const> WaypointServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace tricat_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tricat_msgs/WaypointServiceRequest";
  }

  static const char* value(const ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
;
  }

  static const char* value(const ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::tricat_msgs::WaypointServiceRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TRICAT_MSGS_MESSAGE_WAYPOINTSERVICEREQUEST_H
