// Generated by gencpp from file tricat_msgs/WPList.msg
// DO NOT EDIT!


#ifndef TRICAT_MSGS_MESSAGE_WPLIST_H
#define TRICAT_MSGS_MESSAGE_WPLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tricat_msgs/WP.h>

namespace tricat_msgs
{
template <class ContainerAllocator>
struct WPList_
{
  typedef WPList_<ContainerAllocator> Type;

  WPList_()
    : header()
    , WP_data()  {
    }
  WPList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , WP_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tricat_msgs::WP_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tricat_msgs::WP_<ContainerAllocator> >> _WP_data_type;
  _WP_data_type WP_data;





  typedef boost::shared_ptr< ::tricat_msgs::WPList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tricat_msgs::WPList_<ContainerAllocator> const> ConstPtr;

}; // struct WPList_

typedef ::tricat_msgs::WPList_<std::allocator<void> > WPList;

typedef boost::shared_ptr< ::tricat_msgs::WPList > WPListPtr;
typedef boost::shared_ptr< ::tricat_msgs::WPList const> WPListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tricat_msgs::WPList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tricat_msgs::WPList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tricat_msgs::WPList_<ContainerAllocator1> & lhs, const ::tricat_msgs::WPList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.WP_data == rhs.WP_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tricat_msgs::WPList_<ContainerAllocator1> & lhs, const ::tricat_msgs::WPList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tricat_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tricat_msgs::WPList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tricat_msgs::WPList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tricat_msgs::WPList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tricat_msgs::WPList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tricat_msgs::WPList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tricat_msgs::WPList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tricat_msgs::WPList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6d33a8e2e98aba038773acbcf874e13";
  }

  static const char* value(const ::tricat_msgs::WPList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6d33a8e2e98aba0ULL;
  static const uint64_t static_value2 = 0x38773acbcf874e13ULL;
};

template<class ContainerAllocator>
struct DataType< ::tricat_msgs::WPList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tricat_msgs/WPList";
  }

  static const char* value(const ::tricat_msgs::WPList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tricat_msgs::WPList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"tricat_msgs/WP[] WP_data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tricat_msgs/WP\n"
"std_msgs/Float64 x\n"
"std_msgs/Float64 y\n"
"std_msgs/String type\n"
"std_msgs/UInt16 num\n"
"std_msgs/UInt16 range\n"
"std_msgs/Bool arrive\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt16\n"
"uint16 data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::tricat_msgs::WPList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tricat_msgs::WPList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.WP_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WPList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tricat_msgs::WPList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tricat_msgs::WPList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "WP_data[]" << std::endl;
    for (size_t i = 0; i < v.WP_data.size(); ++i)
    {
      s << indent << "  WP_data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tricat_msgs::WP_<ContainerAllocator> >::stream(s, indent + "    ", v.WP_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRICAT_MSGS_MESSAGE_WPLIST_H
